### ISSUE TITLE
Breadcrumbs React component not rendering properly

### ISSUE THREAD

**Issue by haleyv** [department-of-veterans-affairs/component-library#303]
The VA-Breadcrumbs React component is not rendering as expected in my application.

The React code used is:
```
        <va-breadcrumbs label="Breadcrumbs">
            <a href="https://www.accesstocare.va.gov">Access to Care</a>
            <a href="#">{title}</a>
        </va-breadcrumbs>
```
I tested replacing the href values with "#one" and "#two" as demo'd in the Storybook, with identical results.

Expected result from the Storybook: 
A list of links will be generated; arrows will appear between the links

Actual result is rendered exactly as written:
```
<nav class="va-nav-breadcrumbs" id="va-breadcrumbs">
  <div id="react_0HMFNVKATTRD9">
    <va-breadcrumbs label="Breadcrumbs" data-reactroot="">
<a href="#one">Access to Care</a>
<a href="#two">Outpatient Compare Data</a>
    </va-breadcrumbs>
  </div>
</nav>
```
![image](https://user-images.githubusercontent.com/42793274/155635819-e8f18ac7-b733-47ea-b859-73c78748974f.png)

**Comment by bkjohnson** [comment]
Can you check and see what version of the `@department-of-veterans-affairs/component-library` npm package you have on your branch? Also, let me know if this is still rendered improperly after a `yarn install`.

I'm on master and here is a code example I tried:

```diff
diff --git a/src/applications/coronavirus-vaccination-expansion/containers/App.jsx b/src/applications/coronavirus-vaccination-expansion/containers/App.jsx
index 128db2086a..b7f6e54c76 100644
--- a/src/applications/coronavirus-vaccination-expansion/containers/App.jsx
+++ b/src/applications/coronavirus-vaccination-expansion/containers/App.jsx
@@ -7,14 +7,14 @@ import formConfig from '../config/form';
 export default function App({ location, children }) {
   return (
     <>
-      <Breadcrumbs>
+      <va-breadcrumbs>
         <a href="/">Home</a>
         <a href="/health-care">Health care</a>
         <a href="/health-care/covid-19-vaccine">COVID-19 vaccines at VA</a>
         <a href="/health-care/covid-19-vaccine/stay-informed">
           Sign up to get a vaccine
         </a>
-      </Breadcrumbs>
+      </va-breadcrumbs>
       <RoutedSavableApp formConfig={formConfig} currentLocation={location}>
         {children}
       </RoutedSavableApp>
```

And here's the result:

![va-breadcrumbs rendered in browser](https://user-images.githubusercontent.com/2008881/155637996-e34c9d13-3c52-43f6-85cc-e27ae0144d5f.png)

**Comment by andresriveratoro** [comment]
It looks like you're using our web component `va-breadcrumbs` instead of the React `<Breadcrumbs>` component.

**Comment by haleyv** [comment]
@bkjohnson you're right! I'd taken out the ^ in the package.json reference to component-library. Instead of ^3.3.4 I was just referencing 3.3.4, which doesn't contain the breadcrumbs component. Thanks for your suggestion!

**Comment by bkjohnson** [comment]
:thinking: Limiting the package to major version 3 with the caret still shouldn't have the breadcrumbs web component, it wasn't added until [`v4.1.0`](https://github.com/department-of-veterans-affairs/component-library/releases/tag/v4.1.0)
