### ISSUE TITLE
React components to remove in version 11

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/component-library#333]
## Description

Due to migration to web components, we've got a few React components that are now unused:

### Migration completed or Web Component available

- [x] `Banner`
- [x] `PromoBanner`
- [x] `CollapsiblePanel`
- `CheckboxGroup`
- [x] `TextArea`

### Unused
- `HelpMenu`
- `IconHelp`
- `AcceptTermsPrompt`
- `PrivacyAgreement`

This is to keep track of which React components are unused. Bundling these kinds of removals together into a single version release can keep our major version creep low, which indicates a more stable package. It will also mean less chore work when bumping `component-library` versions in sibling repos.

## Tasks
- [ ] Remove listed components in next major version of the component library

**Comment by k80bowman** [comment]
It looks like `Banner` and `CollapsiblePanel` are no longer used as well!

**Comment by bkjohnson** [comment]
The description has been edited to reflect recent changes.

**Comment by humancompanion-usds** [comment]
This work is being tracked in an epic: 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1530
