### ISSUE TITLE
Audit components to identify internationalization needs for the Check In team and request translations

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/component-library#343]
## Description

Our components have some hard-coded English text. The Check In team has requested that we enable translations for several of our components, so we need to identify everything internal to those components which will need a Spanish translation.

Once we have determined what text needs to be translated, we need to reach out to the Check In team to get the translations from them.

## Details
List of components
- Date (and va-date, since that is in development)
    - Select (and va-select) - used as part of Date (and va-date)
    - NumberInput (and va-number-input, since that is in development)
- va-text-input
- va-loading-indicator
- va-alert
- va-telephone
- va-accordion

It might be helpful to put all of this in a spreadsheet or Confluence table.

## Acceptance criteria
- [ ] Obtain a list of all hard-coded English text for sighted users
- [ ] Obtain a list of all hard-coded `aria-label`s for screen readers
- [ ] Get translations from Check In team

**Comment by k80bowman** [comment]
Good catch I missed that one. Let me ask them how they would like to handle that situation, because it is the same with the va-alert component.

**Comment by k80bowman** [comment]
They are just going to override the value for va-loading-indicator and va-alert. I let them know which props they would need to pass in and made sure they understood that if they don't the text will be in English.

**Comment by k80bowman** [comment]
Spreadsheet with hard-coded values: https://docs.google.com/spreadsheets/d/11a5nfSNhFrju_qLRWNM71cb86oZVe4L4K826xNDDDU8/edit#gid=0

**Comment by k80bowman** [comment]
[Passed](https://dsva.slack.com/archives/C01DBGX4P45/p1649860309441689?thread_ts=1649781669.566199&cid=C01DBGX4P45) spreadsheet to the check-in team.

**Comment by caw310** [comment]
Translations expected 4/27 at the earliest.

**Comment by k80bowman** [comment]
Received initial set of [translations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/translations/SPA-FINAL_CIE%20in-app%20content.json). Closing
