### ISSUE TITLE
Export type definitions for typescript projects

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/component-library#356]
## Description

The component library is [being used in a React typescript project](https://dsva.slack.com/archives/C01DBGX4P45/p1649446167005429) and typescript is throwing an error:

```
Could not find a declaration file for module
```

We should provide a type declaration file for the library.

### Details

The `web-components` sub-package is currently building with `declaration: false`:

https://github.com/department-of-veterans-affairs/component-library/blob/96692e5cd93ad0bb3140342d551b092f9c5d2e83/packages/web-components/tsconfig.json#L5

According to [the tsconfig documentation](https://www.typescriptlang.org/tsconfig#declaration) we may need that to be `true`.

We also declare the location of a type definition file in our `package.json`:

https://github.com/department-of-veterans-affairs/component-library/blob/96692e5cd93ad0bb3140342d551b092f9c5d2e83/packages/web-components/package.json#L9

---

A build in `web-components` currently will create a `dist/types/index.d.ts` file:

![image](https://user-images.githubusercontent.com/2008881/162516751-330f21d2-469a-4a1c-a83d-010afc9b87b9.png)

However, there is no type definition file in the `core` build:

![image](https://user-images.githubusercontent.com/2008881/162517028-d9d58c32-ed09-40ee-83ce-bb9431c26fd9.png)

We also may need to make sure that the `core` package has these type definition files and/or has a `types` property in the `package.json`.

## Acceptance criteria
- [ ] Type definition file is provided for the component library

**Comment by mjknight50** [comment]
Hi @k80bowman   Circling back this open issue.  Is there a plan or roadmap for this from the platform team?

**Comment by mjknight50** [comment]
@humancompanion-usds Our team is interested in moving to typescript and having the declarations for the components library would be very helpful.  Is this something you could help us move along?

**Comment by humancompanion-usds** [comment]
@micahchiang - Do you want to help me prioritize this?

**Comment by micahchiang** [comment]
This is a great idea that we should definitely do. We can add it as a stretch item for the time being, as it feels less urgent than the current things we have slated for sprint 38.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/component-library/356?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @micahchiang @nickjg231 @powellkerry @rmessina1010
