### ISSUE TITLE
Add internationalization capability - NumberInput and va-number-input

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/component-library#359]
## Description
This ticket is dependent on #343. The `va-number-input` portion is dependent on [NumberInput: Web Component Development](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/39550)

Once we have received translations, we need to update the NumberInput and va-number-input components to accommodate internationalization.

## Details
See the [i18next demo PR](https://github.com/department-of-veterans-affairs/component-library/pull/346) for internationalization infrastructure and implementation examples.

## Acceptance Criteria
- [ ] NumberInput component correctly displays translated text when appropriate
- [ ] va-number-input component correctly displays translated text when appropriate
- [ ] tests have been written/updated to cover this functionality

**Comment by caw310** [comment]
Translations expected at the earliest on 4/27.
