### ISSUE TITLE
Add internationalization capacity - Date

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/component-library#362]
## Description
Once we have received translations, we need to update the Date component to accommodate internationalization.

## Details
See the [i18next demo PR](https://github.com/department-of-veterans-affairs/component-library/pull/346) for internationalization infrastructure and implementation examples.

## Acceptance Criteria
- [ ] Date component correctly displays translated text when appropriate
- [ ] tests have been written/updated to cover this functionality

**Comment by caw310** [comment]
Waiting for translations.
