### ISSUE TITLE
CreateOverlayComponent.tsx TypeScript error 

### ISSUE THREAD

**Issue by EClancyVA** [department-of-veterans-affairs/component-library#553]
CreateOverlayComponent.tsx contains a TypeScript error that is showing in our repo.

The error reads: Type _'OverlayComponent & ReactOverlayProps & { forwardedRef: ForwardedRef<OverlayType>; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Overlay> & Readonly<Props>'._

![image](https://user-images.githubusercontent.com/113545409/195652424-8089f2dc-bbd7-4f29-9860-4f1bf8cbbc98.png)
![image](https://user-images.githubusercontent.com/113545409/195652506-ebed3493-41df-4cc5-af10-db85986d1441.png)

**Comment by imelda-guzman** [comment]
This was a user error and has been resolved on our end.  When we updated to the latest version of the component-library and web-components we forgot to update the import path of the VA web components.

Updating the old import path from `@department-of-veterans-affairs/web-components/react-bindings` to `@department-of-veterans-affairs/component-library/dist/react-bindings` along with fixing any TypeScript issues did the trick.

We will close this ticket.
