### ISSUE TITLE
Documentation or steps to import web components into react project

### ISSUE THREAD

**Issue by RookTKO** [department-of-veterans-affairs/component-library#611]
I can't seem to find any actual documentations stating how one should import the new web components into a react projects as a lot of the old react components got deprecated. Are there some steps or urls you could link me to help me out. I'm working on the VANotify and dependabot has a an issue for us to update the library. Any assistance in this matter would be amazing, I would also love to add this to a wiki for reference for anyone else who stumbles upon this same issue I am having.

Is this the only way to import them into a React project? (I'm using vets-website as a reference as it seems they have the webcomponents already working).

https://github.com/department-of-veterans-affairs/vets-website/commit/e7d9476c8b40d5da19f593c52ab0a008284870f5#diff-2d15727208da5a1529aff2690f7f1a64f82360bf6ba8e973f6d519fa3aa2b237

**Comment by caw310** [comment]
This should have some helpful info for you. https://design.va.gov/about/developers#using-web-components

**Comment by Andrew565** [comment]
@RookTKO Did you still need help with this? Noticed the ticket was still open.

**Comment by RookTKO** [comment]
@Andrew565 sorry, I wasn't able to get to it until today. I'll let you now my COB if I still need help, it not I'll close it out.

**Comment by RookTKO** [comment]
Closing the issue for the time being, thank you for the help so far.
