### ISSUE TITLE
Is there documentation on how to import Component Library into a new React project?

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/component-library#647]
Is there documentation on how to import Component Library into a new React project?

**Comment by humancompanion-usds** [comment]
component-library is not currently intended to be used outside of vets-website.

**Comment by mmlumba** [comment]
@humancompanion-usds is this still the case currently? The install page on the VA Design System website implies that the component-library can be used in any project: https://design.va.gov/about/developers/install
